spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JobsApp
    username: root
    password: proiectMSA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  mail:
    host: localhost
    port: 3306
    username: root
    password: proiectMSA

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port : 8081